creation_rules:
  - path_regex: .*\.?dev\.yaml
    encrypted_suffix: 'password'
    key_groups:
      - age:
          - ALICE
          - BOB
  - path_regex: .*\.?prod\.yaml
    key_groups:
      - age:
          - ALICE
