@startuml
skinparam handwritten true
title Déploiement d'une application


actor Développeur

artifact "dépôt git    " {
artifact code
}

storage c #pink;line:red;line.bold;text:black [
"Identifiants de BDD"
]

cloud "Cloud Provider"  {
database bdd [
"base de données"
]
node appli

appli -d-> bdd : stocke Données
}

Développeur - code : Produit

code -d-> "Cloud Provider" : se déploie sur
c -d-> appli : Injection d'identifiant

@enduml
